[headers]
  [[headers]]
    for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"

  [[headers]]
    for = "/google-maps-api/*"
    [headers.values]
      Cache-Control = "no-cache, no-store, must-revalidate"
